all: exercise-2-1 exercise-2-2 exercise-2-3 exercise-2-4 exercise-2-5 exercise-2-6 exercise-2-7 exercise-2-8 exercise-2-9

exercise-2-1: exercise-2-1.c
	gcc exercise-2-1.c -o exercise-2-1

exercise-2-2: exercise-2-2.c
	gcc exercise-2-2.c -o exercise-2-2

exercise-2-3: exercise-2-3.c
	gcc exercise-2-3.c -o exercise-2-3

exercise-2-4: exercise-2-4.c
	gcc exercise-2-4.c -o exercise-2-4

exercise-2-5: exercise-2-5.c
	gcc exercise-2-5.c -o exercise-2-5

exercise-2-6: exercise-2-6.c
	gcc exercise-2-6.c -o exercise-2-6

exercise-2-7: exercise-2-7.c
	gcc exercise-2-7.c -o exercise-2-7

exercise-2-8: exercise-2-8.c
	gcc exercise-2-8.c -o exercise-2-8

exercise-2-9: exercise-2-9.c
	gcc exercise-2-9.c -o exercise-2-9

clean:
	rm -f exercise-2-1
	rm -f exercise-2-2
	rm -f exercise-2-3
	rm -f exercise-2-4
	rm -f exercise-2-5
	rm -f exercise-2-6
	rm -f exercise-2-7
	rm -f exercise-2-8
	rm -f exercise-2-9
