all: exercise-3-2 exercise-3-3-x exercise-3-5 exercise-3-4-x

exercise-3-2: exercise-3-2.c
	gcc -Wall -g exercise-3-2.c -o exercise-3-2

exercise-3-3-x: exercise-3-3-x.c
	gcc -Wall -g exercise-3-3-x.c -o exercise-3-3-x

exercise-3-5: exercise-3-5.c
	gcc -Wall -g exercise-3-5.c -o exercise-3-5

exercise-3-4-x: exercise-3-4-x.c
	gcc -Wall -g exercise-3-4-x.c -o exercise-3-4-x

clean:
	rm -f exercise-3-2
	rm -f exercise-3-3-x
	rm -f exercise-3-5
	rm -f exercise-3-4-x
