all: exercise-1-1 exercise-1-2

exercise-1-1: exercise-1-1.c
	gcc exercise-1-1.c -o exercise-1-1

exercise-1-2: exercise-1-2.c
	gcc exercise-1-2.c -o exercise-1-2

clean:
	rm -f exercise-1-1
	rm -f exercise-1-2
