all: exercise-1-1 exercise-1-2 exercise-1-3 exercise-1-4 \
	 exercise-1-5 exercise-1-6 exercise-1-9 exercise-1-10 \
	 exercise-1-12 exercise-1-13 exercise-1-14 exercise-1-15 \
	 exercise-1-16 exercise-1-17 exercise-1-18  exercise-1-20 exercise-1-21

exercise-1-1: exercise-1-1.c
	gcc -g -Wall exercise-1-1.c -o exercise-1-1

exercise-1-2: exercise-1-2.c
	gcc -g -Wall exercise-1-2.c -o exercise-1-2

exercise-1-3: exercise-1-3.c
	gcc -g -Wall exercise-1-3.c -o exercise-1-3

exercise-1-4: exercise-1-4.c
	gcc -g -Wall exercise-1-4.c -o exercise-1-4

exercise-1-5: exercise-1-5.c
	gcc -g -Wall exercise-1-5.c -o exercise-1-5

exercise-1-6: exercise-1-6.c
	gcc -g -Wall exercise-1-6.c -o exercise-1-6

exercise-1-7: exercise-1-7.c
	gcc -g -Wall exercise-1-7.c -o exercise-1-7

exercise-1-8: exercise-1-8.c
	gcc -g -Wall exercise-1-8.c -o exercise-1-8

exercise-1-9: exercise-1-9.c
	gcc -g -Wall exercise-1-9.c -o exercise-1-9

exercise-1-10: exercise-1-10.c
	gcc -g -Wall exercise-1-10.c -o exercise-1-10

exercise-1-12: exercise-1-12.c
	gcc -g -Wall exercise-1-12.c -o exercise-1-12

exercise-1-13: exercise-1-13.c
	gcc -g -Wall exercise-1-13.c -o exercise-1-13

exercise-1-14: exercise-1-14.c
	gcc -g -Wall exercise-1-14.c -o exercise-1-14

exercise-1-15: exercise-1-15.c
	gcc -g -Wall exercise-1-15.c -o exercise-1-15

exercise-1-16: exercise-1-16.c
	gcc -g -Wall exercise-1-16.c -o exercise-1-16

exercise-1-17: exercise-1-17.c
	gcc -g -Wall exercise-1-17.c -o exercise-1-17

exercise-1-18: exercise-1-18.c
	gcc -g -Wall exercise-1-18.c -o exercise-1-18

exercise-1-20: exercise-1-20.c
	gcc -g -Wall exercise-1-20.c -o exercise-1-20
	
exercise-1-21: exercise-1-21.c
	gcc -g -Wall exercise-1-21.c -o exercise-1-21

clean:
	rm -f exercise-1-1
	rm -f exercise-1-2
	rm -f exercise-1-3
	rm -f exercise-1-4
	rm -f exercise-1-5
	rm -f exercise-1-6
	rm -f exercise-1-7
	rm -f exercise-1-8
	rm -f exercise-1-9
	rm -f exercise-1-10
	rm -f exercise-1-12
	rm -f exercise-1-13
	rm -f exercise-1-14
	rm -f exercise-1-15
	rm -f exercise-1-16
	rm -f exercise-1-17
	rm -f exercise-1-18
	rm -f exercise-1-20
	rm -f exercise-1-21
